"""Add event_id and chunk_type to DocumentChunk

Revision ID: 1a59ed1d4784
Revises: 7e0f727d67aa
Create Date: 2026-03-10 15:18:01.010206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a59ed1d4784'
down_revision: Union[str, Sequence[str], None] = '7e0f727d67aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('event_id', sa.UUID(), nullable=True))
    op.add_column('document_chunks', sa.Column('chunk_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'chunk_type')
    op.drop_column('document_chunks', 'event_id')
    # ### end Alembic commands ###
